[package]
name = "sequenced-broadcast"
version = "0.2.6"
edition = "2021"
authors = ["Patrick Lorio <patrick@methods.dev>"]
description = "Async structure to allow sequenced broadcasts with history"
repository = "https://github.com/Developed-Methods/sequenced-broadcast"
license = "BSD-2-Clause"

[dependencies]
tokio = { version = "1.40", features = ["macros", "sync"] }
arc-metrics = "0.1"

[dev-dependencies]
tokio = { version = "1.40", features = ["full"] }
